### ISSUE TITLE
Tidak optimized di layar dengan resolusi 1366x768

### ISSUE THREAD

**Issue by Reza-Fahlevi** [hafizhrf/Portofilia#4]
Selamat siang Bapack Fabian

Websitenya tidak optimized di layar laptop saya yang kentang pak, mohon segera di perbaiki
![image](https://user-images.githubusercontent.com/33341301/108827747-8e058e00-75f8-11eb-986b-560f80751868.png)

Terimakasih pack

**Comment by hafizhrf** [comment]
> Selamat siang Bapack Fabian
> 
> Websitenya tidak optimized di layar laptop saya yang kentang pak, mohon segera di perbaiki
> ![image](https://user-images.githubusercontent.com/33341301/108827747-8e058e00-75f8-11eb-986b-560f80751868.png)
> 
> Terimakasih pack

noted, terima kasih infonya
